language: r
sudo: false
cache: packages
dist: trusty
r:
  - release

env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=0  # no error if suggested packs are not avail
    - _R_CHECK_TESTS_NLINES_=999

warnings_are_errors: true
r_check_args: "--as-cran --run-donttest"

before_install:
  # we want to see libpaths and installed packages from cache
  - Rscript -e 'message("LIBPATHS:"); .libPaths()'
  - Rscript -e 'message("INSTALLED PACKS:"); installed.packages()[,1:3]'

before_script:
  - Rscript -e 'install.packages("roxygen2")'
  - R --no-save <<< 'library("devtools"); document()'

script:
  - R CMD build .
  - R CMD check typer*.tar.gz --as-cran --run-donttest
  - grep -q -R "WARNING" "typer.Rcheck/00check.log" ; [ $? -ne 0 ]

after_success:
  - git checkout master
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - R --no-save <<< 'library("devtools"); document();'
  - git config user.name Travis
  - git config user.email '<>'
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" >> .git/credentials
  - git config push.default matching
  - git add --force man/*
  - git add DESCRIPTION NAMESPACE
  - git commit -m "update auto-generated documentation [ci skip]" || true
  - git push

after_failure:
  - ./travis-tool.sh dump_logs

on_success: change
on_failure: always

notifications:
  email: false
